version: ~> 1.0
language: c
matrix:
# gcc
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - secure: "W4b3+2QXHRWddzR0MP/8mpppepuHj1SsFXc/u+wjJWiQ59L2L2R+aGJ2e7wh3M26UaxxRdFZr0mcPEUo/EOn2as0oloAeRPt2lS8az3Doih/Wt1xqIAWNPOsY4ljtaValtZFGVOwcQZYePh314pAagQY/e+NoRWBIJ/Tl48AtcOJov4shq0ichp/8/4+DuAprpnRsSYSKPmMI6cYI0EWt0VKgzx+nOLYuORKetOEbqsRm55LIr5vZk5IueE45bqdlyGkwtPvmVg0XNGbLZxiIycZ6V/zvw9UxQy7DlqUjuZT4R5HJ/wIcvgVR9JprBN7Aza9NvTRupghGujoubb3Io6Xl71plpcAqyAjtpzre6IxxfHc7UEjIexK3tOgTBZff3AuR6+AEvVt9VZYh+TLLjx3Vmg4ek5ETvXeYRg4gbkf01obV019MdO1aNJgcOqOHExFuQ3VnxTo1tCDsT4z6pzRly2EXxOxzDWUGJ+c60tsmQzdr9SiQJgvecfxSfO4RCj2sgQ+2zNYWQ/Rk8HAcf+n7Sze/KTJ6DZltSGP6RA6mHbCNj4VQ63JmGhciSIvNaKbwAUaIlNQWFHFtctDFNwVhikEZNLgC+3o0+9apWBvmuHb5is4SlPSlsvYrUOzIZEApUNFlZh5+bNfXL7o1s5qWIvk56rhkYQ9dEWBzzk="
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "theimpossibleastronaut/rmw"
            description: "Console recycle bin written in C"
          notification_email: "andy400-dev@yahoo.com"
          build_command_prepend: "meson builddir && cd builddir"
          build_command: "ninja"
          branch_pattern: coverity_scan

before_install:
  - echo $CC
  - eval "${MATRIX_EVAL}";
  - sudo apt install python3-pip;
  - python3 -m pip install --user meson ninja;
