name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y gettext
    - run: sudo python3 -m pip install meson ninja
    - run: |
        meson builddir
        cd builddir
        ninja -v test

  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig"
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - run: |
        brew update
        brew unlink gettext && brew link --force gettext
        brew install ncurses meson
    - run: |
        meson builddir
        cd builddir
        ninja -v test
