name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y gettext
        sudo python3 -m pip install ninja
        sudo -H python3 -m pip install git+https://github.com/eli-schwartz/meson.git@intl-dep#egg=meson
    - run: |
        meson builddir
        cd builddir
        ninja -v test

  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig:$PKG_CONFIG_PATH"
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - run: |
        brew update
        brew unlink gettext && brew link --force gettext
        brew install ncurses ninja
        brew list -v gettext
        sudo -H python3 -m pip install git+https://github.com/eli-schwartz/meson.git@intl-dep#egg=meson
    - run: |
        if ! meson builddir; then
            cat builddir/meson-logs/meson-log.txt
            exit 1
        fi
        cd builddir
        ninja -v test
